### ISSUE TITLE
 papa_burger_server issue

### ISSUE THREAD

**Issue by Samirtemtem** [Gambley1/yandex-food-delivery-clone#1]
papa_burger_server:
    git: https://github.com/Gambley1/papa-burger-server
project can't run since the server is set on private. Could you provide a demonstration of running the project on local server instead?

**Comment by itsezlife** [comment]
I am sorry, do we know each other? How did you know about my repository and
this project?

пт, 30 июн. 2023 г., 23:49 Samirtemtem ***@***.***>:

**Comment by itsezlife** [comment]
> papa_burger_server: git: https://github.com/Gambley1/papa-burger-server project can't run since the server is set on private. Could you provide a demonstration of running the project on local server instead?

You can't get access to my backend server for free for certain reasons.
